version: '3'
services:
#mssql docker
  eapartman-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PZPpzp123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - eapartmannet

  eapartman-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eApartmanDB=Server=eapartman-sql,1433;Database=eApartman;User=sa;Password=PZPpzp123!;ConnectRetryCount=0
    ports:
      - 5013:80
    networks:
      - eapartmannet      
    links:
      - eapartman-sql
    depends_on:
      - eapartman-sql
      
networks:
  eapartmannet:
    driver: bridge